[package]
name = "yy_dps"
version = "0.1.0"
edition = "2024"

[dependencies]
# makepad-widgets ={ git = "https://github.com/makepad/makepad",branch = "dev"}
makepad-widgets ={ git = "https://github.com/makepad/makepad",rev = "ddcae99b691be2a7fd37e2545b5beafadfe24359"}
toml = "0.9"
serde = { version = "1.0.226", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
sqlx-oldapi = { version = "0.6", features = ["mssql", "macros", "runtime-tokio-rustls", "chrono"], default-features = false}
anyhow = "1.0.100"
thiserror = {version = "2.0"}
umya-spreadsheet = "2.3.3"
rayon = "1.11.0"
rfd ={ version = "0.15.4"}
rand = { version = "0.9.2"}
rand_distr = {version = "0.5.1"}
futures = {version = "0.3.31"}
regex ={ version = "1.12"}
tracing = { version = "0.1.41", default-features = false }
tracing-subscriber = "0.3.0"
rust_xlsxwriter = "0.90"
crossbeam-queue = "0.3.8"
calamine = "0.31"
async-trait = "0.1"

[package.metadata.packager]
product_name = "yy_dps"
identifier = "org.wjz.yy_dps"

icons = ["./packaging/logo.png"]
out_dir = "./dist"

resources = [
    { src = "./dist/resources/makepad_widgets", target = "makepad_widgets" },
    { src = "./dist/resources/yy_dps", target = "yy_dps" },
    { src = "./dist/resources/makepad_fonts_chinese_bold", target = "makepad_fonts_chinese_bold" },
    { src = "./dist/resources/makepad_fonts_chinese_bold_2", target = "makepad_fonts_chinese_bold_2" },
    { src = "./dist/resources/makepad_fonts_chinese_regular", target = "makepad_fonts_chinese_regular" },
    { src = "./dist/resources/makepad_fonts_chinese_regular_2", target = "makepad_fonts_chinese_regular_2" },
    { src = "./dist/resources/makepad_fonts_emoji", target = "makepad_fonts_emoji" },
]
before-each-package-command = """
robius-packaging-commands before-each-package \
    --force-makepad \
    --binary-name yy_dps \
    --path-to-binary ./target/release/yy_dps
"""

[package.metadata.packager.deb]
depends = "./dist/depends_deb.txt"
desktop_template = "./packaging/yy_dps.desktop"
section = "utils"

[package.metadata.packager.macos]
minimum_system_version = "11.0"
frameworks = [ ]
info_plist_path = "./packaging/Info.plist"
entitlements = "./packaging/Entitlements.plist"
signing_identity = "Developer ID Application: AppChef Inc. (SFVQ5V48GD)"


## Configuration for `cargo packager`'s generation of a macOS `.dmg`.
[package.metadata.packager.dmg]
background = "./packaging/Robrix macOS dmg background.png"
window_size = { width = 960, height = 540 }
app_position = { x = 200, y = 250 }
application_folder_position = { x = 760, y = 250 }


## Configuration for `cargo packager`'s generation of a Windows `.exe` setup installer.
[package.metadata.packager.nsis]
## See this: <https://nsis.sourceforge.io/Docs/Chapter4.html#varconstant>
appdata_paths = [
    "$APPDATA/$PUBLISHER/$PRODUCTNAME",
    "$LOCALAPPDATA/$PRODUCTNAME",
]
[profile.release]
opt-level = "s"
lto = true
panic = "abort"
strip = true
codegen-units = 1
