[[Template]]
id = 1
template_name = "249"
create_time = "2024/01/01 10:00:00"
update_time = "2025/08/06 18:25:53"
row = "2"
[Template.infos]
kink = {rondan = false, rondan_min = "", rondan_max = "", rondan_size = "", data_type = "数据", data_select = "kink", fixed_content = "", decimal= "2"}
se = {rondan = false, rondan_min = "", rondan_max = "", rondan_size = "", data_type = "数据", data_select = "se", fixed_content = "", decimal= "3"}
ith = {rondan = true, rondan_min = "0.7", rondan_max = "1.5", rondan_size = "10", data_type = "数据", data_select = "ith", fixed_content = "", decimal= "2"}

bosa_vbr1 = {rondan = false, rondan_min = "", rondan_max = "", rondan_size = "", data_type = "固定内容", data_select = "", fixed_content = "2025", decimal= ""}

[Template.tables]
E3 = "EEE"
F4 = "fff"
E8 = "Date"
A1 = "Test"

